// Secret shop item list

"CardList"
{
	"1"		"item_bottle"
	"2"		"item_ring_of_health"
	"3"		"item_void_stone"
	"4"		"item_energy_booster"
	"5"		"item_vitality_booster"
	"6"		"item_point_booster"
	"7"		"item_platemail"
	"8"		"item_talisman_of_evasion"
	"9"		"item_hyperstone"
	"10"	"item_ultimate_orb"
	"11"	"item_demon_edge"
	"12"	"item_mystic_staff"
	"13"	"item_reaver"
	"14"	"item_eagle"
	"15"	"item_relic"
}